### PR TITLE
Added all http methods/verbs

### PR DESCRIPTION
**Pull request by thekemkid**
I listed them in the order they're presented here: https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Summary_table

### CODE REVIEW

**Comment by mcollina** [comment]
LGTM

**Comment by mcollina** [comment]
Seems tests are failing

**Comment by thekemkid** [comment]
For some reason we test to ensure 'client does not supports HEAD'

Why?

**Comment by mcollina** [comment]
Maybe we don't support it. LOL.

**Comment by thekemkid** [comment]
But... why wouldn't we support it? Why do we explicitly test for non-support? 😂

There's more lines of code in testing for non-support rather than _just_ supporting it. 😂

**Comment by mcollina** [comment]
I _remember_ that I had *good reasons* not to do it, so important reasons that I completely forgot about them.

**Comment by thekemkid** [comment]
😂

I have a good reason to support it: We are a http 1.1 bench marker. we should support it :P

The final call is up to you, should I fix the tests, or remove HEAD support? These are all which are supported by wrk: https://github.com/wg/wrk/blob/master/src/http_parser.c#L960-L974

**Comment by mcollina** [comment]
please go ahead.

**Comment by thekemkid** [comment]
I assume go ahead is to mean fix tests... on it! 😄

**Comment by thekemkid** [comment]
@mcollina I know you have been so excited for this update... but its ready for a re-review! 😄 I moved the valid array of http methods to their own file, for testability purposes. Hope this is okay 👍

**Pull request merged**
