### PR TITLE
Feature make samples variable

### PR DESCRIPTION
**Pull request by drewva**
Hopefully this actually works because I didn't test it with every configuration since I figured you all probably have that automated. I did play around with some configurations though.

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Could you add a unit test?

**Comment by drewva** [comment]
Would you rather I add unit tests to the existing testing files & then commit them, or should I provide a single, new file that tests all of the things I added?

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
linting is failing, could you take a look?

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
