### PR TITLE
fix: Report (full) response body correctly (#275)

### LINKED ISSUE #275: Response body is not handled correctly
I've found the following issue in the response handling:

## The issue

When the response data is sufficiently large (not sure what the threshold is), `onResponse` is called multiple times, each time with a partial body. This makes it really hard to e.g. validate the response body, like checking whether it is valid JSON and matches a certain structure.

The `expectedBody` feature is also broken because it's checked multiple times, again against partial body data, instead of the full response body.

## The reason

This is because `Client` checks `expectedBody` and calls `onResponse` every time `this.parser[HTTPParser.kOnBody]` fires. However, this can happen multiple times per response, and the handler will be passed a partial body every time.

## The fix

This can be fixed by

1. recording the full body in `resData[this.cer]` (e.g. via a new `body` field), and
2. only checking `expectedBody` and calling `onResponse` (via `this.requestIterator.recordBody()`) once in the `HTTPParser.kOnMessageComplete` handler.

### PR DESCRIPTION
**Pull request by Jannis**
This fixes #275 by implementing the fix described in the issue.

### CODE REVIEW

**Comment by Jannis** [comment]
Yup, I can try!

**Comment by Jannis** [comment]
@mcollina I'm actually not sure how to simulate a response that would lead to `HTTPParser.kOnBody` being called twice. I've been able to test this fix against a real server though.

**Comment by mcollina** [comment]
Maybe you can use a mock.

**Comment by blanchma** [comment]
Hi guys, we have being following this issue because we had it too. Is this going to merge?

**Comment by mcollina** [comment]
Not in this current form as it is missing a test. Would you like to contribute one?

**Comment by salmanm** [comment]
@mcollina Let's close this.

**Pull request closed without merging**
