### PR TITLE
removed node 10

### PR DESCRIPTION
**Pull request by mcollina**

### CODE REVIEW

**Comment by Fdawgs** [comment]
Did the CI just give up the ghost on this PR?

**Comment by mcollina** [comment]
can you push a new commit?

**Comment by Fdawgs** [comment]
> 
> 
> can you push a new commit?

I think the actions can just be reran at https://github.com/mcollina/autocannon/pull/371/checks

**Comment by mcollina** [comment]
I tried that but there is no "rerun" button at the top. Please rebase or add a commit here.

**Pull request closed without merging**
