### PR TITLE
Expose printResult internal

### PR DESCRIPTION
**Pull request by fraxken**
Hi,

The goal of this pull request is to expose the printResult internal function. I guess it need review, some of the things i was not sure:

- I created the printResult-process.js at the root of test (not sure if this is the right place).
- I used one of my result for fixtures/example-result (maybe the name and the content of the file need to be replaced).

I haven't tested all options yet.. I wanted to be sure the way i'm doing it is ok.

PR related to https://github.com/mcollina/autocannon/issues/296 

Best Regards,
Thomas

### CODE REVIEW

**Comment by mcollina** [comment]
I would highly prefer to expose a function that returns a string and do not print directly to the console. This will require some changes to `printResult`.

**Comment by fraxken** [comment]
Ok. I dedicated my Wednesday and Thursday on open-source this week. I will make an update to the PR at that time.

**Comment by mcollina** [comment]
thanks!!!

**Comment by fraxken** [comment]
Hello 👋

I started to make the necessary modifications. I added a new printResultAPI.js file in lib to avoid having to modify code directly in the autocannon root file.

For printResult i was not sure how to do it exactly
- I was thinking of using outputStream with a WritableStream but it would surely make printResultAPI Asynchronous (for no good reason i guess).
- One of my option was to return a string if outputStream was undefined or null (But I didn't necessarily want to introduce any inconsistency or break the existing code).

So finally i decided to go with a new parameter and a naïve solution and get your feedback on it.

**Comment by mcollina** [comment]
I would prefer to have it always return a string.

**Comment by fraxken** [comment]
Updated again. I was thinking you wanted to always return a string but only for API.

**Review by mcollina — COMMENTED** [review]
Code is ok!

**Comment by fraxken** [comment]
I removed the Draft status of the PR.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Good work!

**Pull request merged**
