### PR TITLE
assume onPort if -- node is set

### PR DESCRIPTION
**Pull request by karankraina**
Adds support for #180 

@mcollina Please review when you have some time.

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
I think we can just remove `--onPort`.

Remember to adjust the docs.

**Comment by karankraina** [comment]
Thanks for your review @mcollina . Also, if we remove onPort flag, I think the check should not striclty be restricted to `-- node`. We should assume on Port if `-- <any-script>` is provided. Your thoughts ?

**Comment by mcollina** [comment]
Ah, that's true. Then, this is good. Can you just update the docs?

**Comment by karankraina** [comment]
Sure, updating.

**Comment by karankraina** [comment]
@mcollina Does it look okay to you?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by karankraina** [comment]
@mcollina checks on node v14 on mac and node v20 on windows are failing. Can see other merges with these fails too. Any known issues ?

**Comment by mcollina** [comment]
Drop node 14 and v16 support, I'll bump
the major.

windows is likely flaky.

**Comment by karankraina** [comment]
Should I add v22 ?

**Comment by mcollina** [comment]
yes please

**Comment by karankraina** [comment]
Done but windows still not happy. I think we need another issue to address that. And if this looks good, can we merge it?

**Comment by karankraina** [comment]
@mcollina

**Comment by mcollina** [comment]
I'll look into the windows tests asap.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
