### PR TITLE
feat: implement request titles

### PR DESCRIPTION
**Pull request by RafaelGSS**
Obs: This is just a sketch just to validate if we can reach the goal. The things need to be refactored and cover some paths.

Ref #319 

<details>
  <summary>Result example of `samples/requests-sample.js` - Click here!</summary>
  
```sh
{
  title: undefined,
  url: 'http://localhost:41135',
  socketPath: undefined,
  connections: 1000,
  pipelining: 1,
  workers: undefined,
  duration: 10.32,
  start: 2021-01-27T00:07:40.581Z,
  finish: 2021-01-27T00:07:50.905Z,
  errors: 0,
  timeouts: 0,
  mismatches: 0,
  non2xx: 0,
  resets: 0,
  '1xx': 0,
  '2xx': 225408,
  '3xx': 0,
  '4xx': 0,
  '5xx': 0,
  requests: [
    {
      title: '1-',
      latencies: {
        average: 45.71,
        mean: 45.71,
        stddev: 97.15,
        min: 17,
        max: 1255,
        p0_001: 17,
        p0_01: 17,
        p0_1: 17,
        p1: 18,
        p2_5: 19,
        p10: 35,
        p25: 36,
        p50: 36,
        p75: 38,
        p90: 40,
        p97_5: 45,
        p99: 331,
        p99_9: 1237,
        p99_99: 1253,
        p99_999: 1255
      },
      requests: {
        average: 7565.2,
        mean: 7565.2,
        stddev: 844.1,
        min: 5120,
        max: 8003,
        total: 225408,
        p0_001: 5123,
        p0_01: 5123,
        p0_1: 5123,
        p1: 5123,
        p2_5: 5123,
        p10: 5123,
        p25: 7515,
        p50: 8003,
        p75: 8003,
        p90: 8003,
        p97_5: 8003,
        p99: 8003,
        p99_9: 8003,
        p99_99: 8003,
        p99_999: 8003
      },
      throughput: {
        average: 1013299.2,
        mean: 1013299.2,
        stddev: 112913.23,
        min: 686080,
        max: 1072127,
        total: 30204672,
        p0_001: 686591,
        p0_01: 686591,
        p0_1: 686591,
        p1: 686591,
        p2_5: 686591,
        p10: 686591,
        p25: 1007103,
        p50: 1072127,
        p75: 1072127,
        p90: 1072127,
        p97_5: 1072127,
        p99: 1072127,
        p99_9: 1072127,
        p99_99: 1072127,
        p99_999: 1072127
      },
      status: { '1xx': 0, '2xx': 75632, '3xx': 0, '4xx': 0, '5xx': 0 }
    },
    {
      title: '2-',
      latencies: {
        average: 43.62,
        mean: 43.62,
        stddev: 7.78,
        min: 15,
        max: 76,
        p0_001: 15,
        p0_01: 15,
        p0_1: 16,
        p1: 19,
        p2_5: 21,
        p10: 37,
        p25: 40,
        p50: 44,
        p75: 49,
        p90: 52,
        p97_5: 55,
        p99: 58,
        p99_9: 73,
        p99_99: 75,
        p99_999: 76
      },
      requests: {
        average: 7516.4,
        mean: 7516.4,
        stddev: 994.32,
        min: 4608,
        max: 8027,
        total: 225408,
        p0_001: 4611,
        p0_01: 4611,
        p0_1: 4611,
        p1: 4611,
        p2_5: 4611,
        p10: 4611,
        p25: 7515,
        p50: 8003,
        p75: 8003,
        p90: 8003,
        p97_5: 8027,
        p99: 8027,
        p99_9: 8027,
        p99_99: 8027,
        p99_999: 8027
      },
      throughput: {
        average: 1006848,
        mean: 1006848,
        stddev: 133095.44,
        min: 617472,
        max: 1076223,
        total: 30204672,
        p0_001: 617983,
        p0_01: 617983,
        p0_1: 617983,
        p1: 617983,
        p2_5: 617983,
        p10: 617983,
        p25: 1007103,
        p50: 1072127,
        p75: 1072127,
        p90: 1072127,
        p97_5: 1076223,
        p99: 1076223,
        p99_9: 1076223,
        p99_99: 1076223,
        p99_999: 1076223
      },
      status: { '1xx': 0, '2xx': 75144, '3xx': 0, '4xx': 0, '5xx': 0 }
    },
    {
      title: '3-',
      latencies: {
        average: 45,
        mean: 45,
        stddev: 7.93,
        min: 18,
        max: 86,
        p0_001: 18,
        p0_01: 18,
        p0_1: 19,
        p1: 21,
        p2_5: 23,
        p10: 38,
        p25: 41,
        p50: 46,
        p75: 50,
        p90: 52,
        p97_5: 58,
        p99: 61,
        p99_9: 84,
        p99_99: 86,
        p99_999: 86
      },
      requests: {
        average: 7465.2,
        mean: 7465.2,
        stddev: 1003.85,
        min: 4608,
        max: 8003,
        total: 225408,
        p0_001: 4611,
        p0_01: 4611,
        p0_1: 4611,
        p1: 4611,
        p2_5: 4611,
        p10: 4611,
        p25: 7491,
        p50: 8003,
        p75: 8003,
        p90: 8003,
        p97_5: 8003,
        p99: 8003,
        p99_9: 8003,
        p99_99: 8003,
        p99_999: 8003
      },
      throughput: {
        average: 999884.8,
        mean: 999884.8,
        stddev: 134315.56,
        min: 617472,
        max: 1072127,
        total: 30204672,
        p0_001: 617983,
        p0_01: 617983,
        p0_1: 617983,
        p1: 617983,
        p2_5: 617983,
        p10: 617983,
        p25: 1003519,
        p50: 1072127,
        p75: 1072127,
        p90: 1072127,
        p97_5: 1072127,
        p99: 1072127,
        p99_9: 1072127,
        p99_99: 1072127,
        p99_999: 1072127
      },
      status: { '1xx': 0, '2xx': 74632, '3xx': 0, '4xx': 0, '5xx': 0 }
    }
  ]
}
```
</details>

Also, I'm not sure if the results are consistent. @mcollina What do you think, it would be a great feature with this structure or perhaps a way to extend the `autocannon` and provide a plugin with this approach is better?

### CODE REVIEW

**Comment by RafaelGSS** [comment]
@mcollina ping

**Review by mcollina — CHANGES_REQUESTED** [review]

**Comment by RafaelGSS** [comment]
Yes I know that there are some things to refactor, I just created this draft to validate with you if these major changes would be nice to have, in other terms: The requests now have an owned section of `throughput`, `latencies`, `requests`. For instance, we'll change the current approach of aggregate all the data together to split it into requests.

So, It's valid to move forward?

**Comment by mcollina** [comment]
I think it's valid but the current implementation would be problematic.

**Comment by RafaelGSS** [comment]
@mcollina Sorry for the late. I've spent a short time last night on it and I've decided that even if `autocannon` own this feature wouldn't be different than using more than one instance of `autocannon`.

So, I've decided to abort this PR since it would take some time due hot paths as you mentioned and re-design of the current implementation.

Anyway, I solved my issue regarding this feature request. Thanks.

**Pull request closed without merging**
