### PR TITLE
Allow for ID replacement in the URL

### LINKED ISSUE #512: Is there a way to generate a url for each request?
I'd like to benchmark `POST` requests where I could pass a random id at the end of path.
I tried using `setupClient` to change the url, but I'll only change the first request of each client.

### PR DESCRIPTION
**Pull request by MattIPv4**
Resolves #512

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by MattIPv4** [comment]
👋 @mcollina it looks like a single test job failed here, which prevented automerge. Could you trigger a re-run of the failed job?

**Comment by GlenTiki** [comment]
That test has failed on rerun twice more. Three fails seems unlikely to be flakey tests - this might be an edgecase on node 20 on windows. Possibly in node?

**Comment by GlenTiki** [comment]
That test is failing on main, anyway. Merging since its not a problem with your code.

**Pull request merged**
